Models/ErrorViewModel.cs
namespace CP1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace CP1.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Contato()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using CP1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CP1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;

namespace CP1.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult Info()
        {
            return View();
        }
    }
}

Controllers/ListaJogosController.cs
using Microsoft.AspNetCore.Mvc;

namespace CP1.Controllers
{
    public class ListaJogosController : Controller
    {
        public IActionResult ListaJogos()
        {
            return View();
        }
    }
}

Views/Contato/Contato.cshtml
@{
    ViewData["Title"] = "Contato";
}

<div class="text-center">
    <h1>Contato</h1>
    <h3>Para mais informações, entre em contato em: <a href="https://github.com/thiagogz/CPsCSharp">GitHub</a></h3>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<div class="text-center">
    <h1 class="display-4">Essa página é meramente ilustrativa.</h1>
    <p> Para mais informações, seguir para a página "Informações"</p>
</div>

Views/Info/Info.cshtml
@{
    ViewData["Title"] = "Informações";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <h2> Você está prestes a testemunhar a análise mais duvidosa dos melhores jogos de 2023.</h2>
    <h3> Aqui, você pode discordar de tudo, menos da primeira colocação.</h3>
    <h4> A lista foi feita com muito carinho e estudo.</h4>
    <h5> Ainda assim, além da primeira colocação, podem haver informações não condizentes com a opinião de meros mortais.</h5>
    <h6> Divirta-se.</h6>
    <p> Para reclamações, clique <a href="https://github.com/thiagogz/CPsCSharp">aqui</a>.</p>
</div>

Views/ListaJogos/ListaJogos.cshtml
@{
    ViewData["Title"] = "ListaJogos";
}

<div class="text-center">
    <h1>TOP 5 melhores jogos de 2023</h1>
    <ul>
        <li>1. Baldur's Gate 3</li>
        <li>2. The Legend of Zelda: The Tears of the Kingdom</li>
        <li>3. Super Mario Bros. Wonder</li>
        <li>4. Marvel’s Spider-Man 2</li>
        <li>5. Alan Wake II</li>
    </ul>
    <h3>Caso discorde, favor, enviar sua opinião <a href="https://github.com/thiagogz/CPsCSharp">aqui</a></h3>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CP1 - C# - Thiago Zupelli</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CP1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CP1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Info" asp-action="Info">Informações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListaJogos" asp-action="ListaJogos">Lista de Jogos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Contato">Contato</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CP1 - <a asp-area="" asp-controller="Main" asp-action="Main">Início</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>